# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Package
        run: npm run package

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name || github.event.inputs.version }}
          release_name: Release ${{ github.ref_name || github.event.inputs.version }}
          body: |
            ## What's Changed
            
            * See the [CHANGELOG.md](CHANGELOG.md) for detailed changes
            
            ## Installation
            
            ```yaml
            - uses: your-username/sensitive-scanner-action@${{ github.ref_name || github.event.inputs.version }}
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
            ```
            
            ## Full Changelog
            
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v1.0.0...${{ github.ref_name || github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Update major version tag
        run: |
          VERSION=${{ github.ref_name || github.event.inputs.version }}
          MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -fa $MAJOR_VERSION -m "Update $MAJOR_VERSION tag"
          git push origin $MAJOR_VERSION --force

  marketplace:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to GitHub Marketplace
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./action.yml
          asset_name: action.yml
          asset_content_type: text/yaml
