name: Test My Action

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Call your action using the local path
      - name: Test my action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          custom-patterns: '["password.*","maytheforcebewithyou"]'
